### ISSUE TITLE
Calling EasingTypes non-explicitly...

### ISSUE THREAD

**Issue by Prodical** [hideakitai/Tween#10]
Hiya hideakitai

I'm using your library to control some DMX RGBW LED strips... it's working well ;-)

I'm now coding some timeline 'presets'  - a data structure/file that holds multiple iterations of the initial, hold and easing values for each of the RGBW channels - which I'll then use to update the current timeline using the functionality in your dynamic_append example.

Where I'm stuck is in trying to find a way to declare the easingType non-explicitly so i can store and recall different ones in the update i.e.

tl[tlNo]->add(rVal).init(initVal[0]).then<easeType[0]>...

rather than

tl[tlNo]->add(rVal).init(initVal[0]).then<Ease::Sine>...

I thought creating a list of the structs in the utils/Easing/Easing/Types.h would be the way to go... but I'm struggling to find the correct syntax and/or namespace to initialise the list...

Any advice on how I might realise this - and it doesn't have to be via a list - would be much appreciated.

Best

Lewis

**Comment by hideakitai** [comment]
Template args should be static. So you can't directly use a value of a dynamic list inside it. One solution is creating a switch-case by the value of easing type list (but it's so redundant...

```c++
switch (ease_types[i]) {
  case Ease::Sine:
    ~~~.then<Ease::Sine>(...)
  case Ease::Bounce:
    ~~~.then<Ease::Elastic>(...)
  case Ease::Bounce:
    ~~~.then<Ease::Bounce>(...)
  ...
}
```

**Comment by hideakitai** [comment]
Though I close this issue, please feel free to reopen or continue this issue if you still need help. (Maybe slow to respond, sorry)
