### ISSUE TITLE
Easing function not working in Github version library

### ISSUE THREAD

**Issue by lunarifish** [hideakitai/Tween#12]
- Board: NodeMCU-32S(ESP32-S)
- PlatformIO Core: 6.1.11
- Platform: espressif32
- Framework: Arduino

Easing function worked differently in Github version and PlatformIO version of the library. Github version seemed to be not working correctly.

![123.png](https://img1.imgtp.com/2023/09/02/OZoMxUGK.png)

Code:
```C++
#include <Arduino.h>
#include <Tween.h>

Tween::Timeline tml;
double target = 0;

void setup() {
    Serial.begin(9600);
    tml.add(target)
        .init(0)
        .then<Ease::Elastic>(2, 2000);
    tml.start();
}

void loop() {
    tml.update();
    Serial.println(target);
}
```

**Comment by hideakitai** [comment]
Thank you for reporting. I will check it when I have time...

**Comment by hideakitai** [comment]
Fixed. Thank you!
