### ISSUE TITLE
Arduino crashes after multiple rounds of updating the timeline

### ISSUE THREAD

**Issue by atoav** [hideakitai/Tween#18]
Hi, thanks for the nice to use library!

## What I was trying

I wanted to create an animation that is randomized between each run. My naive idea was to just check if the timeline is not running, and then clear it, create a new sequence and restart it. I then wanted to have another longer running timeline that happens on every nth round.

## What I encountered

The counter for the rounds kept resetting at around 11, with all kind of other weird things happening, likely an indication that the arduino is crashing.

I went and took everything weird out and made a minimal example that reproduces the Error (on an Arduino Nano R3):

```C++
#include <Tween.h>
#define LED_PIN 5

int baseSpeed = 20;

unsigned long blink_count = 0;
float led_value = 0.0f;

Tween::Timeline timeline;


void setup() {
  Serial.begin(115200);

  // Setup LED Pin
  pinMode(LED_PIN, OUTPUT);

  // LED timeline mode
  timeline.mode(Tween::Mode::ONCE);
}

void loop() {
  timeline.update();

  if (!timeline.isRunning()) {
    timeline.clear();
    timeline.add(led_value, true)
            .then(1.0f, baseSpeed*5)
            .then(0.9f, baseSpeed*5)
            .then(0.0f, baseSpeed*10)
            .hold(baseSpeed*5);
    timeline.restart();
    
    // Count rounds
    blink_count++;
    Serial.print("Round ");
    Serial.println(blink_count);
  }

  // Set the LED brightness
  analogWrite(LED_PIN, int(led_value * 255));
}
```

The Serial output looks as follows:  

```
12:04:40.738 -> Round 1
12:04:41.254 -> Round 2
12:04:41.737 -> Round 3
12:04:42.252 -> Round 4
12:04:42.766 -> Round 5
12:04:43.250 -> Round 6
12:04:43.762 -> Round 7
12:04:44.243 -> Round 8
12:04:44.759 -> Round 9
12:04:45.272 -> Round 10
12:04:45.754 -> Round 11
12:04:46.269 -> Round 1
12:04:46.783 -> Round 2
12:04:47.265 -> Round 3
12:04:47.781 -> Round 4
```
This loops forever an never shows any number above 11. The garbled characters after Round 11 indicate something went wrong before. My expectation would be that the Round should count up till a integer overflow happens on `unsigned long blink_count`

**Comment by sjernigan** [comment]
FWIW, your code ran fine on a Feather M0 without repeats...I killed it at round 200.

**Comment by hideakitai** [comment]
@atoav Hmm.. I confirmed the problem. I think it's a problem of ArxContainer (map<T, U> for Uno) or ArxSmartPtr (shared_ptr<T> for Uno), but maybe it takes time to solve this problem (Because I don't have the motivation to support AVR chips). 

If you are fine changing the board, I recommend using a powerful board like ESP32.

**Comment by hideakitai** [comment]
If you still need help, please feel free to reopen this issue.
