### ISSUE TITLE
retriggering sequences

### ISSUE THREAD

**Issue by sjernigan** [hideakitai/Tween#19]
First off, thanks for the library.  I think it is going to work perfectly but I’d like to check how I’m using it as I’m a little confused by the templating.

I’d like to trigger multiple sequences repeatedly in response to events.  I’m assuming this means that the timeline should continue to run and that I should add (or retrigger) sequences as needed.  

I have the timeline set to REPEAT_TL mode and auto_erase set to true.  

To the dynamic_append example, I have added the following to the “switch” conditionals
        } else if (c == 'e') {
            Serial.println("Add e");
            ep = (float*) malloc(sizeof(float));
            *ep = 0;
            timeline.add(*ep,true).init(0).then(14, 5000).then(0, 2000, []() {
                  Serial.println("e is finished, destroy e");
                  free(ep);
                  ep = NULL;
              });
            timeline.update_duration();
     }

This seems to work but is there a simpler way….for instance resetting the 'a' sequence and adding it back in.  Perhaps it would take the addition of an indefinite hold method in addition to the reset.  That way the sequence could stay in the timeline until it was ready to be triggered.  An example of this scenario would be great.

**Comment by hideakitai** [comment]
I'm sorry, I couldn't understand what you'd like to do... Could you explain more details with some drawings?

**Comment by sjernigan** [comment]
Thank you for responding.  Actually I thought I had it working but didn't.  Here's the scenario

I have some tweens I wish to retrigger multiple times.  Lets say we have
Tween A defined as  init(0).then(10, 5000).then(0, 2000)
and
Tween B defined as init(0).then(100,5000).then(0,5000)

Imagine these tweens are triggered by two buttons (A and B).  The A button is pushed at T=2 and T = 10.  The B button is pushed at T= 5.

If I printed the values every second, I would expect something like (if the Tween isn't running, it holds it's value and would be initialized to 0)
T    A   B
0    0    0
1    0    0
2    0    0
3    2    0
4    4    0
5    6    0
6    8    20
7    10   40
8    5    60
9    0    80
10  0    100
11   2    80
12   4   60
13   6   40
14   8   20
15   10  0
16   5   0
17   0   0
...

But what I see is that the tween starts at some random point in the sequence like it's initial start time isn't being set correctly.  Will submit a code example and output shortly.

**Comment by sjernigan** [comment]
#include <Tween.h>

Tween::Timeline timeline;

float* ep = NULL;

void setup() {
    Serial.begin(115200);
    delay(2000);
    timeline.mode(Tween::Mode::REPEAT_TL);
    timeline.auto_erase(true);

    timeline.start();  // must be started to tween items in timeline
}

void loop() {
    timeline.update();  // must be called to update tween in timeline

    // show plot if timeline runs in 10sec
    if (Serial.available()) {
        char c = Serial.read();

        if (c == 'e') {
            if (ep != NULL) {
              Serial.println("E still running");
            } else {
              Serial.println("Add e");
              ep = (float*) malloc(sizeof(float));
              *ep = 0;
              timeline.add(*ep,true).init(0).then(14, 5000).then(0, 2000, []() {
                    Serial.println("e is finished, destroy e");
                    free(ep);
                    ep = NULL;
                });
              timeline.update_duration();            
              }
        } else if (c == 'c') {
            Serial.println("Clear");
            timeline.clear();
            timeline.update_duration();
            //timeline.start();
        } else if (c == 's') {
            timeline.stop();
            Serial.println("Stopped");
        } else if (c == 'r') {
            timeline.update_duration();
            timeline.start();
            Serial.println("Started");
        }
    }

    // adjust serial ouput
    static uint32_t prev_ms = millis();
    if (millis() > prev_ms + 1000) {
        if (timeline.isRunning()) {
          Serial.print(timeline.size());
          Serial.print(" ");
          Serial.print(timeline.isRunning());
          Serial.print(" e:");
          if(ep!=NULL) {
            Serial.println((float)*ep);
          } else {
            Serial.println("-");
          }
        }
        prev_ms = millis();
        delay(50);
    }
}



Here's the output I get from a Feather M0, comments added to explain
21:02:55.326 -> 0 1 e:-          //no sequences running but the timeline is running
21:02:55.841 -> Add e           //e sequence added    
21:02:56.304 -> 1 1 e:1.35    ///initiallized to zero correctly
21:02:57.313 -> 1 1 e:4.15
21:02:58.318 -> 1 1 e:6.95
21:02:59.328 -> 1 1 e:9.76
21:02:59.537 -> E still running  //tried to readded, correctly identified as still running
21:03:00.307 -> 1 1 e:12.56
21:03:01.326 -> 1 1 e:10.59
21:03:02.304 -> 1 1 e:3.59
21:03:02.815 -> e is finished, destroy e     //e sequence finishes and calls the callback
21:03:03.318 -> 0 1 e:-                                //no sequences running, timeline continues to run
21:03:04.319 -> 0 1 e:-
21:03:05.083 -> Add e                                  //another e is added
21:03:05.333 -> 1 1 e:6.97                            //value does not initialize to 0
21:03:06.302 -> 1 1 e:9.78
21:03:07.329 -> 1 1 e:12.58
21:03:08.310 -> 1 1 e:10.54
21:03:09.319 -> 1 1 e:3.54
21:03:09.815 -> e is finished, destroy e
21:03:10.332 -> 0 1 e:-
21:03:11.312 -> 0 1 e:-
21:03:12.305 -> 0 1 e:-
21:03:13.307 -> 0 1 e:-
21:03:14.062 -> Add e
21:03:14.338 -> 1 1 e:12.60        //a third e sequence is triggered, this time it seems to start the sequence on the downward slope
21:03:15.339 -> 1 1 e:10.50
21:03:16.316 -> 1 1 e:3.49
21:03:16.816 -> e is finished, destroy e
21:03:17.333 -> 0 1 e:-

**Comment by hideakitai** [comment]
`update_duration()` does not reset a timeline. Please use `timeline.restart()` to restart the timeline from zero. You can check the current elapsed time of the timeline by `timeline.sec()`.

**Comment by sjernigan** [comment]
I believe that would restart the entire timeline...interrupting other running tweens.  I don't think this library will work for me but I can use your easing library directly.  Thanks for your attention.

**Comment by hideakitai** [comment]
If you want to switch between completely different sequences applied to the same target, it would be best to have multiple timelines and switch between the timelines themselves.
