### ISSUE TITLE
Question: How do I make the timeline loop?

### ISSUE THREAD

**Issue by akaalias** [hideakitai/Tween#2]
Hi Hideataki! 

Thank you so much for this library. 

I would like to simply fade a single LED in and out in a loop. But with the code below, it only does the fade-in and fade-out once - even though I'm using Tween::Mode::LOOP. Can you please tell me what I'm missing? 

```
int led = 9;           // the PWM pin the LED is attached to

#include <Tween.h>

Tween::Timeline timeline;
float target = 0.f;

// the setup routine runs once when you press reset:
void setup() {
  timeline.add(target) // target tweens
        .then(255, 2000)  // to 10 in 5000[ms]
        .then(0, 2000);  // then to 0 in 5000[ms]

  timeline.mode(Tween::Mode::LOOP); // loop sequence if finished
  timeline.start();
    
  // declare pin 9 to be an output:
  pinMode(led, OUTPUT);
}

// the loop routine runs over and over again forever:
void loop() {

  timeline.update(); // must be called to tween target


  analogWrite(led, target);
}
```

**Comment by hideakitai** [comment]
@akaalias Sorry, there was a bug and fixed! Please note that `Mode::LOOP` has renamed to `Mode::REPEAT` because it conflicts with macro `LOOP` only defined in AVR... :-( Please check it out, Thanks!

**Comment by akaalias** [comment]
@hideakitai - Amazing, thank you so, so much. 🙏🏻 It works now exactly as expected. With best wishes from Berlin, Alexis
