### ISSUE TITLE
Library breaks with more than 3 sequences

### ISSUE THREAD

**Issue by pliniobarraza** [hideakitai/Tween#23]
Everything works fine with up to three variables being sequenced. But as soon as a fourth target is added the sketch stops working. 

This happens on Arduino Uno (ATMEGA328P)

However it seems to be working on an Arduino Mega (AT,EGA2560) up to 12 targets but not more. If these are the limitations perhaps you could explain this on the documentation so we are not wondering why things stop working.

Thank you for the lib anyway ;)

**Comment by hideakitai** [comment]
ATMEGA328 has limited memory, so you can't run many tweens. Please consider a more powerful MCU.
