### ISSUE TITLE
Storing Sequence object in a variable

### ISSUE THREAD

**Issue by Osmiogrzesznik** [hideakitai/Tween#3]
Hi, I was trying to use your library to create arduino program that would accept sequence of keyframes through serial and dynamically add new Transitions to sequence in the timeline. It seems that when i am storing the sequence reference returned from timeline.add() that arduino restarts on calling .then() method.
I was trying to educate myself on C++ past week but i think i know even less now. 
Is it possible to store the Sequence for later and dynamically add new Transitions while in the arduinos loop() function?

**Comment by hideakitai** [comment]
@Osmiogrzesznik Hi, please try

```C++
timeline[0].then(...);
```

I don't know if it works because I haven't designed this library for dynamic change... but it may work

**Comment by Osmiogrzesznik** [comment]
this is VScode error, but arduino IDE allowed that
![image](https://user-images.githubusercontent.com/28631235/136650465-c26cc739-02b8-4e3d-9f30-1a730b466f93.png)
this is the code i was running
```cpp
int a = 0;
bool deb = false;
int lastentered = 0;
Tween::Timeline mytimeline;
// this was my first try and then trying to call member methods on sq
// Tween::sequence::Sequence<int> sq = mytimeline.add(a).init(0).then(100, 1000).then(0, 1000);
void setup()
{
  Serial.begin(9600);
  Serial.println("Starting test...");
  Serial.println("a,lastentered");
  mytimeline.add(a).init(0).then(100, 1000).then(0, 1000);
}

void loop()
{
  if (Serial.available() > 0)
  {
    char c = Serial.read();
    switch (c)
    {
    case 'k':

      lastentered = Serial.parseInt();
      Serial.print("entered: ");
      Serial.println(lastentered);

      mytimeline[0].then(lastentered, 1000);
      break;
    case 'a':
      mytimeline.start();
      break;
    case 'b':
      mytimeline.stop();
      break;
    case 'd':
      deb = !deb;
      break;
    }
  }

  static uint32_t prev_ms = millis();
  if (millis() > prev_ms + 100 && deb)
  {
    Serial.print(a);
    Serial.print(", ");
    Serial.print(lastentered);
    Serial.println();
    prev_ms = millis();
  }
  mytimeline.update();
}
```

unfortunately the result in the serial monitor:

```
09:06:54.590 -> a,lastentered
09:07:31.528 -> Starting test...
09:07:31.528 -> a,lastentered
09:07:37.233 -> entered: 10
09:07:38.221 -> ⸮⸮EM⸮M⸮M⸮M⸮M⸮M⸮M⸮M⸮M⸮M⸮M⸮M⸮⸮t⸮⸮⸮⸮tStStStStStStStStStStStSt⸮⸮⸮⸮t⸮⸮⸮M⸮M⸮M⸮M⸮M⸮ (and this continues)
```

something similar happens when i try commented out approach .

**Comment by hideakitai** [comment]
@Osmiogrzesznik Thanks! I've supported adding transitions dynamically in v0.3.6. If you still have a problem, let me know please! `dynamic_append` example may be helpful for you.
