### ISSUE TITLE
Feature request: Pass timestamp to update function

### ISSUE THREAD

**Issue by DOCaCola** [hideakitai/Tween#7]
It might be helpful to be able to manually pass the current timestamp to the update function (as an overload). This way the animation could be stopped and resumed later, or (re)started from mid-sequence.

**Comment by hideakitai** [comment]
Hi, you can do it with `FrameRateCounter`'s APIs. Please refer to it.

> `Timeline` is derived from [FrameRateCounter](https://github.com/hideakitai/PollingTimer). So its methods to control timeline are also available. Some useful methods are listed below.

```C++
virtual void start();  // overridden by Tween::Timeline
virtual void stop();
virtual void play();
virtual void pause();
virtual void restart();  // overridden by Tween::Timeline
virtual void clear();    // overridden by Tween::Timeline

void startFromSec(const double from_sec);
void startForSec(const double for_sec, const bool loop = false);
void startFromForSec(const double from_sec, const double for_sec, const bool loop = false);

bool isRunning() const;
bool isPausing() const;
bool isStopping() const;

double sec();  // get current time of timeline
```
