### ISSUE TITLE
hasStopped returning wrong value

### ISSUE THREAD

**Issue by foofel** [hideakitai/Tween#8]
Hey, i am using your nice library on an esp32, but i was able to reproduce the error in visual studio for better debugging. The problem is, that if one calls any function that calls microsec() after an `timeline.update()` the `prev_running` variable is set to false, the next call to `timeline.hasStopped()` then returns `false`. I attached a small example:

```
#define _USE_MATH_DEFINES
#include "Tween.h"

#include <iostream>
#include <thread>

void main() {
	Tween::Timeline tl;
	float myval = 5;
	while(true) {
		tl = Tween::Timeline();
		tl.add(myval)
			.init(0)
			.then(1, 1000);
		tl.start();
		while (!tl.hasStopped()) {
			tl.update();
			//auto a = tl.getDurationMsec();
			auto b = tl.msec();
			std::this_thread::sleep_for(std::chrono::milliseconds{ 500 });
			std::cout << "Value: " << myval << ", has stopped : " << tl.hasStopped() << std::endl;
		}
		std::cout << "next" << std::endl;
	}
}
```

this loop will never print "next", as `timline.hasStopped()` is always false.

if it helps, you can replace your platform error in `PollingTimer.h` with
```
//#error THIS PLATFORM IS NOT SUPPORTED
#include <chrono>
long long myGetTime() {
    static long long start = std::chrono::high_resolution_clock::now().time_since_epoch().count() / 1000;
    return std::chrono::high_resolution_clock::now().time_since_epoch().count() / 1000 - start;
}
#define MICROS() myGetTime()
```
to run it locally on any moderately recent c++ compiler

**Comment by hideakitai** [comment]
@foofel Thanks for reporting. Fixed by https://github.com/hideakitai/PollingTimer/pull/4
